### ISSUE TITLE
Error in Authenticating 

### ISSUE THREAD

**Issue by awaisse003** [plaid/plaid-python-legacy#8]
I am using this lib and trying to connect with Plaid . when i enter my client_id , secret it do not work for me.

> `import` json
`
```
from plaid import Client

Client.config({
    'url': 'https://sandbox.plaid.com',
    'suppress_http_errors': True,
})

client = Client(client_id='5b7704a1c834010013d105f8', secret='REDACTED')

response = client.connect('bofa', {
    'username': 'user_good',
    'password': 'pass_good'
})

user = response.json()
print(user)
```

response is : ` ``{'display_message': None, 'error_code': 'INVALID_HEADERS', 'error_message': 'Content-Type must be one of [application/json]', 'error_type': 'INVALID_REQUEST', 'request_id': '5g4yh'}
`

I want to get start with this Plaid API. i have tried other Lib too (plaid-python) but i have got no luck. can you post a demo code that connects to API via python for my credentials.Thanks

**Comment by awaisse003** [comment]
please : 
PLAID_CLIENT_ID=5b7704a1c834010013d105f8 \
PLAID_SECRET=REDACTED \
PLAID_PUBLIC_KEY=REDACTED \

**Comment by nathankot** [comment]
@awaisse003 please do not post your API credentials on a public forum such as this :(

This repo is for our legacy API, https://github.com/plaid/plaid-python is definitely the one that you want to look at.

I suggest reading through our Quickstart: https://plaid.com/docs/quickstart/
It seems like the piece that you are missing is that you need to use Plaid Link in order to authenticate your users (covered in our docs)
